# Generated by Django 6.0.3 on 2026-06-04 00:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Mamlakat nomi')),
            ],
            options={
                'verbose_name': 'Mamlakati',
                'verbose_name_plural': 'Mamlakatlari',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Janri nomi')),
            ],
            options={
                'verbose_name': 'Janri',
                'verbose_name_plural': 'Janrlari',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Rejissor ismi')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(120)], verbose_name='Rejissor yoshi')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.country', verbose_name='Rejissor yurti')),
            ],
            options={
                'verbose_name': 'Rejissori',
                'verbose_name_plural': 'Rejissorlari',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Film nomi')),
                ('description', models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Film haqida')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Film premyerasi')),
                ('duration', models.CharField(blank=True, max_length=50, null=True, verbose_name='Davomiyligi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Filmdan suratlar')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country', verbose_name='Mamlakati')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.director', verbose_name='Rejissor')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.genre', verbose_name='Janri')),
            ],
            options={
                'verbose_name': 'Kino',
                'verbose_name_plural': 'Kinolar',
            },
        ),
    ]
